# Generated by Django 5.2.11 on 2026-02-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vet', '0007_vet_qte_vignette_niveau_5_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VignetteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(unique=True, verbose_name='Niveau')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description / Équipement')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock Actuel')),
                ('seuil_alerte', models.PositiveIntegerField(default=10, verbose_name="Seuil d'Alerte")),
            ],
            options={
                'verbose_name': 'Catégorie de Vignette',
                'verbose_name_plural': 'Catégories de Vignettes',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée (Achat/Approvisionnement)'), ('sortie', 'Sortie (Utilisation VET)'), ('ajustement', 'Ajustement (Inventaire/Correction)')], max_length=20, verbose_name='Type de Mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaires')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vet_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_vignettes', to='vet.vet', verbose_name='Référence VET')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.vignettecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
