# Generated by Django 5.2.11 on 2026-03-11 12:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('a_frais_exploitation', models.BooleanField(default=False, help_text="Ce type a-t-il les frais annuels d'exploitation?")),
                ('a_contribution_fonds', models.BooleanField(default=False, help_text='Ce type a-t-il la contribution annuelle au fonds universel?')),
                ('a_renouvellement', models.BooleanField(default=False, help_text="Ce type a-t-il un renouvellement d'autorisation?")),
                ('a_frais_instruction', models.BooleanField(default=True, help_text="Ce type a-t-il des frais d'instruction de dossier?")),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'entité",
                'verbose_name_plural': "Types d'entités",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nom_entite', models.CharField(max_length=255, verbose_name='Nom / Raison Sociale')),
                ('province', models.CharField(db_index=True, max_length=100)),
                ('localite', models.CharField(db_index=True, max_length=100)),
                ('quartier_zone', models.CharField(db_index=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('precision_gps', models.CharField(default='Précision inconnue', max_length=50)),
                ('frais_instruction_dossier', models.DecimalField(blank=True, decimal_places=2, help_text="Frais d'instruction de dossier", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('frais_exploitation_annuel', models.DecimalField(blank=True, decimal_places=2, help_text="Frais annuel d'exploitation (redevance annuelle)", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('contribution_fonds_universel', models.DecimalField(blank=True, decimal_places=2, help_text='Contribution annuelle au fonds du service universel', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut_autorisation', models.CharField(choices=[('attribution', 'Attribution'), ('renouvellement', 'Renouvellement'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='attribution', max_length=20)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entites_creees', to=settings.AUTH_USER_MODEL)),
                ('type_entite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='activites.typeactivite')),
            ],
            options={
                'verbose_name': 'Entité',
                'verbose_name_plural': 'Entités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('autorisation', 'Autorisation'), ('renouvellement', 'Renouvellement'), ('rapport', 'Rapport'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='entites/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'png'])])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='activites.activite')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Document d'entité",
                'verbose_name_plural': "Documents d'entité",
                'ordering': ['-date_upload'],
            },
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['type_entite', 'numero'], name='entites_ent_type_en_219750_idx'),
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['province', 'localite'], name='entites_ent_provinc_770971_idx'),
        ),
    ]
