# Generated by Django 5.2.11 on 2026-03-11 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_d_emission',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date d'émission de la redevance"),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_d_expiration',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date d'expiration de la redevance"),
        ),
        migrations.AddField(
            model_name='activite',
            name='dossier_suivi_par',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dossier suivi par'),
        ),
        migrations.AddField(
            model_name='activite',
            name='frais_de_dossier_payes',
            field=models.BooleanField(default=False, verbose_name='Frais de dossier payés'),
        ),
        migrations.AddField(
            model_name='activite',
            name='redevance_payee',
            field=models.BooleanField(default=False, verbose_name='Redevance annuelle payée'),
        ),
        migrations.AddField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], db_index=True, default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='activite',
            name='telephone',
            field=models.CharField(blank=True, help_text='Format: +243123456789 ou (243) 123-456789', max_length=20, validators=[django.core.validators.RegexValidator(message='Format de numéro invalide', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.CreateModel(
            name='ActiviteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('payment', 'Paiement')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails des changements')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date/Heure')),
                ('entite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='activites.activite')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit (Entité)",
                'verbose_name_plural': "Journaux d'audit (Entité)",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entite', '-timestamp'], name='entites_ent_entite__42bbce_idx')],
            },
        ),
    ]
