# Generated by Django 5.2.11 on 2026-03-11 14:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_entite_date_d_emission_entite_date_d_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='contrepartie_financiere',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Contrepartie financière associée à l'autorisation (valeur constante définie par le régulateur).", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
