# Generated by Django 5.2.11 on 2026-03-12 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0003_entite_contrepartie_financiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activite',
            new_name='activites_a_type_en_f68f0e_idx',
            old_name='entites_ent_type_en_219750_idx',
        ),
        migrations.RenameIndex(
            model_name='activite',
            new_name='activites_a_provinc_e153f0_idx',
            old_name='entites_ent_provinc_770971_idx',
        ),
        migrations.RenameIndex(
            model_name='activiteauditlog',
            new_name='activites_a_entite__77a371_idx',
            old_name='entites_ent_entite__42bbce_idx',
        ),
        migrations.AlterField(
            model_name='activite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitedocument',
            name='fichier',
            field=models.FileField(upload_to='activites/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'png'])]),
        ),
    ]
