# Generated by Django 5.2.11 on 2026-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0004_rename_entites_ent_type_en_219750_idx_activites_a_type_en_f68f0e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeactivite',
            name='a_frais_instruction',
            field=models.BooleanField(default=False, help_text="Ce type a-t-il des frais d'instruction de dossier?"),
        ),
    ]
