# Generated by Django 5.2.11 on 2026-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_alter_typeactivite_a_frais_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='date_attribution',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_d_emission',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_d_expiration',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_renouvellement',
        ),
        migrations.AddField(
            model_name='activite',
            name='date_debut_autorisation',
            field=models.DateField(blank=True, help_text="Date à laquelle l'autorisation de l'entité prend effet.", null=True, verbose_name="Date de début de l'autorisation"),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_emission_redevance',
            field=models.DateField(blank=True, db_index=True, help_text='Date à laquelle la redevance annuelle a été facturée.', null=True, verbose_name="Date d'émission de la redevance"),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_expiration_redevance',
            field=models.DateField(blank=True, db_index=True, help_text='Date à laquelle la redevance annuelle expire.', null=True, verbose_name="Date d'expiration de la redevance"),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_fin_autorisation',
            field=models.DateField(blank=True, help_text="Date à laquelle l'autorisation de l'entité expire.", null=True, verbose_name="Date de fin de l'autorisation"),
        ),
    ]
