# Generated by Django 5.2.11 on 2026-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0006_remove_activite_date_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='presence_autorisation',
            field=models.BooleanField(default=False, verbose_name='Autorisation présente ?'),
        ),
        migrations.AddField(
            model_name='activite',
            name='presence_facture',
            field=models.BooleanField(default=False, verbose_name='Facture présente ?'),
        ),
        migrations.AddField(
            model_name='activite',
            name='presence_homologation',
            field=models.BooleanField(default=False, verbose_name='Homologation présente ?'),
        ),
    ]
