# Generated by Django 5.2.11 on 2026-03-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0007_activite_presence_autorisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='date_debut_autorisation',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_fin_autorisation',
        ),
    ]
