# Generated by Django 5.2.11 on 2026-03-17 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0008_remove_activite_date_debut_autorisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='activiteauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'audit (Activité)", 'verbose_name_plural': "Journaux d'audit (Activité)"},
        ),
        migrations.AlterModelOptions(
            name='activitedocument',
            options={'ordering': ['-date_upload'], 'verbose_name': "Document d'activité", 'verbose_name_plural': "Documents d'activité"},
        ),
        migrations.AlterModelOptions(
            name='typeactivite',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': "Type d'activité", 'verbose_name_plural': "Types d'activités"},
        ),
        migrations.RemoveIndex(
            model_name='activite',
            name='activites_a_type_en_f68f0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='activiteauditlog',
            name='activites_a_entite__77a371_idx',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='nom_entite',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='type_entite',
        ),
        migrations.RemoveField(
            model_name='activiteauditlog',
            name='entite',
        ),
        migrations.RemoveField(
            model_name='activitedocument',
            name='entite',
        ),
        migrations.AddField(
            model_name='activite',
            name='nom_activite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom / Raison Sociale'),
        ),
        migrations.AddField(
            model_name='activite',
            name='type_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='activites.typeactivite'),
        ),
        migrations.AddField(
            model_name='activiteauditlog',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='activites.activite'),
        ),
        migrations.AddField(
            model_name='activitedocument',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='activites.activite'),
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['type_activite', 'numero'], name='activites_a_type_ac_da3399_idx'),
        ),
        migrations.AddIndex(
            model_name='activiteauditlog',
            index=models.Index(fields=['activite', '-timestamp'], name='activites_a_activit_2587d4_idx'),
        ),
    ]
