# Generated by Django 5.2.11 on 2026-03-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0009_alter_activite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='nom_activite',
            field=models.CharField(max_length=255, verbose_name='Nom / Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='type_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='activites.typeactivite'),
        ),
        migrations.AlterField(
            model_name='activitedocument',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='activites.activite'),
        ),
    ]
