# Generated by Django 5.2.11 on 2026-02-23 08:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VET',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='N°')),
                ('numero_de_la_redevance_annuelle', models.CharField(max_length=50, unique=True, verbose_name='N° DE LA REDEVANCE ANNUELLE')),
                ('identification_de_l_exploitant_ou_raison_sociale', models.CharField(max_length=255, verbose_name="IDENTIFICATION DE L'EXPLOITANT OU RAISON SOCIALE")),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='REGION')),
                ('zone', models.CharField(db_index=True, max_length=100, verbose_name='ZONE')),
                ('quartier', models.CharField(db_index=True, max_length=100, verbose_name='QUARTIER')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('numero_de_telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de numéro invalide', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='NUMERO DE TELEPHONE')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='EMAIL')),
                ('frais_de_dossier_payes', models.BooleanField(default=False, verbose_name='FRAIS DE DOSSIER PAYÉS')),
                ('montant_de_la_redevance_annuelle', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='MONTANT DE LA REDEVANCE ANUELLE')),
                ('montant_total_a_recouvrer', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='MONTANT TOTAL À RECOUVRER')),
                ('date_d_emission_de_la_redevance_annuelle', models.DateField(db_index=True, verbose_name="DATE D'EMISSION DE LA REDEVANCE ANNUELLE")),
                ('date_d_expiration_de_la_redevance_annuelle', models.DateField(db_index=True, verbose_name="DATE D'EXPIRATION DE LA REDEVANCE ANNUELLE")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], db_index=True, default='actif', max_length=20, verbose_name='STATUT')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='NOTES')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='DATE DE CRÉATION')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='DATE DE MISE À JOUR')),
            ],
            options={
                'ordering': ['-date_mise_a_jour'],
                'indexes': [models.Index(fields=['region', 'zone', 'quartier'], name='vet_vet_region_bdfac4_idx'), models.Index(fields=['statut', 'date_d_expiration_de_la_redevance_annuelle'], name='vet_vet_statut_9c7686_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_d_expiration_de_la_redevance_annuelle__gte', models.F('date_d_emission_de_la_redevance_annuelle'))), name='vet_expiration_gte_emission'), models.CheckConstraint(condition=models.Q(('montant_de_la_redevance_annuelle__gte', 0)), name='vet_montant_nonneg')],
            },
        ),
    ]
