# Generated by Django 5.2.11 on 2026-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='numero_de_la_redevance_annuelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='N° DE LA REDEVANCE ANNUELLE'),
        ),
    ]
