# Generated by Django 5.2.11 on 2026-02-23 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_alter_vet_numero_de_la_redevance_annuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='quantite_vignette',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='QUANTITÉ DE VIGNETTES'),
        ),
        migrations.AddField(
            model_name='vet',
            name='type_equipement',
            field=models.CharField(choices=[('niveau_1', 'Niveau 1 (250 FCFA)'), ('niveau_2', 'Niveau 2 (500 FCFA)'), ('niveau_3', 'Niveau 3 (1250 FCFA)'), ('niveau_4', 'Niveau 4 (1750 FCFA)')], default='niveau_1', max_length=20, verbose_name="TYPE D'ÉQUIPEMENT"),
        ),
    ]
