# Generated by Django 5.2.11 on 2026-02-23 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_vet_quantite_vignette_vet_type_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='quantite_vignette',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='type_equipement',
        ),
        migrations.AddField(
            model_name='vet',
            name='qte_vignette_niveau_1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qté Vignettes Niv 1 (250 FCFA)'),
        ),
        migrations.AddField(
            model_name='vet',
            name='qte_vignette_niveau_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qté Vignettes Niv 2 (500 FCFA)'),
        ),
        migrations.AddField(
            model_name='vet',
            name='qte_vignette_niveau_3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qté Vignettes Niv 3 (1250 FCFA)'),
        ),
        migrations.AddField(
            model_name='vet',
            name='qte_vignette_niveau_4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qté Vignettes Niv 4 (1750 FCFA)'),
        ),
    ]
