# Generated by Django 5.2.11 on 2026-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_remove_vet_quantite_vignette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='dossier_suivi_par',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOSSIER SUIVI PAR'),
        ),
    ]
