# Generated by Django 5.2.11 on 2026-02-27 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0006_rename_redevance_to_ordre_recette'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='qte_vignette_niveau_5',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qté Vignettes Niv 5 (2500 FCFA)'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='numero_ordre_de_recette',
            field=models.CharField(max_length=100, unique=True, verbose_name='N° ORDRE DE RECETTE'),
        ),
    ]
