# Generated by Django 5.2.11 on 2026-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0007_vet_qte_vignette_niveau_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='redevance_payee',
            field=models.BooleanField(default=False, verbose_name='REDEVANCE ANNUELLE PAYÉE'),
        ),
    ]
