# Generated by Django 5.2.11 on 2026-03-03 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('vet', '0008_vet_redevance_payee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='qte_vignette_niveau_1',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='qte_vignette_niveau_2',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='qte_vignette_niveau_3',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='qte_vignette_niveau_4',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='qte_vignette_niveau_5',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails des changements')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.vet', verbose_name='VET')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VETVignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.vignettecategory', verbose_name='Catégorie de Vignette')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes_assignees', to='vet.vet')),
            ],
            options={
                'verbose_name': 'Vignette assignée',
                'verbose_name_plural': 'Vignettes assignées',
                'unique_together': {('vet', 'categorie')},
            },
        ),
    ]
