# Generated by Django 5.2.11 on 2026-03-04 07:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0009_remove_vet_qte_vignette_niveau_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='montant_total_a_recouvrer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='MONTANT TOTAL À RECOUVRER'),
        ),
    ]
