# Generated by Django 5.2.11 on 2026-03-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0010_alter_vet_montant_total_a_recouvrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VETDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='vet_documents/%Y/%m/', verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('photo', 'Photo / Image'), ('scan', 'Scan Document (PDF)'), ('other', 'Autre')], default='photo', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vet.vet', verbose_name='Dossier VET')),
            ],
            options={
                'verbose_name': 'Document VET',
                'verbose_name_plural': 'Documents VET',
                'ordering': ['-date_upload'],
            },
        ),
    ]
