# Generated by Django 5.2.11 on 2026-03-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0011_vetdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='montant_total_a_recouvrer',
        ),
    ]
