# Generated by Django 5.2.11 on 2026-03-10 14:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0012_remove_denormalized_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Précision: ±0.111 km (6 décimales)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Précision: ±0.111 km (6 décimales)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='numero_ordre_de_recette',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='N° ORDRE DE RECETTE'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='fichier',
            field=models.FileField(upload_to='vet_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'doc', 'docx', 'txt', 'xls', 'xlsx'])], verbose_name='Fichier'),
        ),
    ]
