
# Generated by Django 5.2.11 on 2026-03-17 08:54

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='Administrateurs')
    Group.objects.create(name='Agents de terrain')
    Group.objects.create(name='Comptables')

class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0013_fix_gps_precision_and_validation'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
