# Generated by Django 5.2.11 on 2026-03-17 09:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0014_create_groups'),
    ]

    operations = [
    ]
