# Generated by Django 5.2.11 on 2026-03-17 09:20

from django.db import migrations

def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Groupes
    admin_group, _ = Group.objects.get_or_create(name='Administrateurs')
    agent_group, _ = Group.objects.get_or_create(name='Agents de terrain')
    comptable_group, _ = Group.objects.get_or_create(name='Comptables')

    # Ensure ContentTypes exist
    vet_content_type, _ = ContentType.objects.get_or_create(app_label='vet', model='vet')
    activite_content_type, _ = ContentType.objects.get_or_create(app_label='activites', model='activite')

    # Ensure some standard permissions exist (Django normally creates them)
    # If they don't exist in the test DB yet, we create them
    def ensure_permission(ct, codename, name):
        p, created = Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={'name': name}
        )
        return p

    # Standard permissions for VET
    ensure_permission(vet_content_type, 'view_vet', 'Can view vet')
    ensure_permission(vet_content_type, 'add_vet', 'Can add vet')
    ensure_permission(vet_content_type, 'change_vet', 'Can change vet')
    ensure_permission(vet_content_type, 'delete_vet', 'Can delete vet')

    # Standard permissions for Activite
    ensure_permission(activite_content_type, 'view_activite', 'Can view activite')
    ensure_permission(activite_content_type, 'add_activite', 'Can add activite')
    ensure_permission(activite_content_type, 'change_activite', 'Can change activite')
    ensure_permission(activite_content_type, 'delete_activite', 'Can delete activite')

    # Refresh querysets
    vet_permissions = Permission.objects.filter(content_type=vet_content_type)
    activite_permissions = Permission.objects.filter(content_type=activite_content_type)

    # Administrateurs
    admin_group.permissions.set(list(vet_permissions) + list(activite_permissions))

    # Agents de terrain
    agent_permissions = [
        p for p in vet_permissions if p.codename.startswith(('view_', 'add_', 'change_'))
    ] + [
        p for p in activite_permissions if p.codename.startswith(('view_', 'add_', 'change_'))
    ]
    agent_group.permissions.set(agent_permissions)

    # Comptables
    comptable_permissions = [
        p for p in vet_permissions if p.codename.startswith('view_')
    ] + [
        p for p in activite_permissions if p.codename.startswith('view_')
    ] + [
        Permission.objects.get(content_type=vet_content_type, codename='change_vet'),
        Permission.objects.get(content_type=activite_content_type, codename='change_activite'),
    ]
    comptable_group.permissions.set(comptable_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0015_assign_permissions'),
        ('activites', '0006_remove_activite_date_attribution_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_permissions),
    ]
