# Generated by Django 5.2.11 on 2026-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0016_assign_permissions_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='possede_vignettes',
            field=models.BooleanField(default=True, verbose_name='VIGNETTES PRÉSENTES ?'),
        ),
        migrations.AddField(
            model_name='vet',
            name='presence_autorisation',
            field=models.BooleanField(default=False, verbose_name='AUTORISATION PRÉSENTE ?'),
        ),
        migrations.AddField(
            model_name='vet',
            name='presence_facture',
            field=models.BooleanField(default=False, verbose_name='FACTURE PRÉSENTE ?'),
        ),
        migrations.AddField(
            model_name='vet',
            name='presence_homologation',
            field=models.BooleanField(default=False, verbose_name='HOMOLOGATION PRÉSENTE ?'),
        ),
    ]
